baseURL: "/"
title: "Jett's blog"
languageCode: "en-us"
theme: "archie"
copyright: "© Jett Chen"
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
googleAnalytics: G-SEJ19RP99Z

params:
  mode: "auto"
  subtitle: "A blog about CTFs, OSINT, Machine learning, and technology."
  social:
    - name: "GitHub"
      icon: "github"
      url: "https://github.com/JettChenT"
    - name: "Twitter"
      icon: "twitter"
      url: "https://twitter.com/jettchen5"
    
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "All posts"
      url: "/posts"
      weight: 2
    # - name: "TIL"
    #   url: "/TIL"
    #   weight: 3
    - name: "About"
      url: "/about"
      weight: 5
    - name: "Tags"
      url: "/tags"
      weight: 4
    - name: "Contact"
      url: "/contact"
      weight: 6
